### ISSUE TITLE
How to specify LATEXMLINPUTS

### ISSUE THREAD

**Issue by physikerwelt** [dginev/LaTeXML-Plugin-ltxmojo#13]
We recently switched from https://github.com/dginev/LaTeXML-Plugin-ltxpsgi/ to https://github.com/dginev/LaTeXML-Plugin-ltxmojo

For the DRMF we used a [custom LATEXMLINPUTS path.](https://github.com/DRMF/operations-puppet-drmf/blob/ab9a24aace044a085a2c0a55e5eef9bb752e725a/templates/latexml.conf.erb#L9) I configured the same environment variable for the container
```
/opt/ltxmojo # perl -de1
  DB<1> print $ENV{'LATEXMLINPUTS'};
/DRMF
  DB<2> exit
```
But on the client-side, @andreg-p sees the following error
```
Error:missing-file:DRMF.xsl No stylesheet 'DRMF.xsl' found!
Use of uninitialized value $stylesheet in concatenation (.) or string at /usr/local/share/perl5/site_perl/LaTeXML/Post/XSLT.pm line 46.

Error:expected:stylesheet Stylesheet '' is not a usable stylesheet!
```
Have you any suggestions on how to proceed.

**Comment by AndreG-P** [comment]
I think by the following error, @physikerwelt meant this:
```
Error:missing-file:DRMF.xsl No stylesheet 'DRMF.xsl' found!
Use of uninitialized value $stylesheet in concatenation (.) or string at /usr/local/share/perl5/site_perl/LaTeXML/Post/XSLT.pm line 46.

Error:expected:stylesheet Stylesheet '' is not a usable stylesheet!
```

**Comment by dginev** [comment]
From what I can see LATEXMLINPUTS is also set in ltxmojo here:
https://github.com/dginev/LaTeXML-Plugin-ltxmojo/blob/master/lib/LaTeXML/Plugin/LtxMojo.pm#L81

You may want to check with using absolute paths, to avoid any relative path resolution issues based on where the web service is started.

**Comment by AndreG-P** [comment]
It seems the path is actually loading. However, I also have another problem. We also preload `[dvipsnames]xcolor.sty`. As you can see, the path `/DRMF` is actually in consideration...

Note also, the error message is not a typo, it actually says `dvipsnam` is missing instead of `dvipsnames` which we load. Do you think it might be a version problem?

```
Warning:missing_file:dvipsnam Can't find definitions dvipsnam
	at xcolor.sty.ltxml; line 52
	Anticipate undefined macros or environments
	search paths are /opt/ltxmojo, /DRMF
	In Core::Definition::Primitive[\ds@dvips... /usr/local/share/perl5/site_perl/LaTeXML/Package/xcolor.sty.ltxml; line 52


Conversion complete: No obvious problems.

Error:missing-file:DRMF.xsl No stylesheet 'DRMF.xsl' found!
Use of uninitialized value $stylesheet in concatenation (.) or string at /usr/local/share/perl5/site_perl/LaTeXML/Post/XSLT.pm line 46.

Error:expected:stylesheet Stylesheet '' is not a usable stylesheet!

Post-processing complete: No obvious problems
Status:conversion:0 
```

**Comment by AndreG-P** [comment]
By the way, setting the absolute path `/DRMF/DRMF.xsl` does not work also.

**Comment by dginev** [comment]
That file should be in the texlive installation, which you need for `dvipsnames` colors. So you should double-check you have a  texlive installed that kpsewhich can see:

```
$ kpsewhich dvipsnam.def
/usr/share/texlive/texmf-dist/tex/latex/graphics/dvipsnam.def
```

I can also never remember if this is available in the main texlive package, or you need the latex extra extension... Not at all friendly for deploying to new machines.

**Comment by dginev** [comment]
Odd. I just verified that latexmlc also would fail if the stylesheet path was passed in via the LATEXMLINPUTS env variable, but it would succeed with the usual `--path` argument. So there may be a missing connection...

**Comment by dginev** [comment]
Ok, so this seems to be finding my made up stylesheet in `/tmp/some/path/DRMF.xsl` just fine. Setup:
```
LATEXMLINPUTS=/tmp/some/path/ morbo script/ltxmojo
```

call:
```
curl -d 'profile=math&stylesheet=DRMF&source=test' http://localhost:3000/convert
```

The key thing I remembered now is that you must provide a `profile` name if you want to use LATEXMLINPUTS, since it's loaded externally. It's a bit of a hacky undocumented feature in the first place. It should be a little easier to use `latexmls --path` instead of ltxmojo for these custom deployments.

**Comment by dginev** [comment]
I should further amend my comment - the `profile` is needed to make `latexmlc` work with LATEXMLINPUTS, since it doesn't explicitly respect it. The `ltxmojo` executable itself will handle the environmental variable even if no profile is given. So this call also finds the stylesheet in my example setup above:

```
curl -d 'stylesheet=DRMF&source=test' http://localhost:3000/convert
```

**Comment by AndreG-P** [comment]
There was something strange in my setup. We fixed the problem. We find DRMF.xsl and also the dvipsnames problem is solved. 

So it seems to work as it should now.

**Comment by dginev** [comment]
Excellent!
